# Generated by Django 4.1.3 on 2022-11-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='Enter field documentation', max_length=20)),
                ('nombre_completo', models.CharField(help_text='Enter field documentation', max_length=20)),
            ],
        ),
    ]
